data:
  root: data/csd
max_eval_sentences: 8
max_eval_tokens: 6000
max_sentences: 32
max_tokens: 20480
model:
  hop_size: 256
  name: shallow
  num_mels: 80
  sampling_rate: 22050
seed: 1234
task_cls: tasks.shallow.ShallowTask
train:
  batch_size: 16
  epochs: 300
vocoder:
  pretrained_checkpoint: checkpoints/0109_hifigan_bigpopcs_hop128
  use_pretrained: true
work_dir: checkpoints/csd_ds_training
